/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DanielDeJesus
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumeroDeFilas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumeroDeColumnas = new javax.swing.JTextField();
        cmbOperaciones = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenadoManual = new javax.swing.JButton();
        cmdLlenadoAutomatico = new javax.swing.JButton();
        cmdOperacion = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Iniciales"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("No. de Filas:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));
        jPanel2.add(txtNumeroDeFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 30, -1));

        jLabel3.setText("No. de Columnas: ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));
        jPanel2.add(txtNumeroDeColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 30, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 170, 100));

        cmbOperaciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recorrido 1", "Recorrido 2", "Recorrido 3", "Recorrido 4", "Recorrido 5" }));
        jPanel1.add(cmbOperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 130, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmdLlenadoManual.setText("Manual");
        cmdLlenadoManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoManualActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenadoManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        cmdLlenadoAutomatico.setText("Automático");
        cmdLlenadoAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenadoAutomaticoActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLlenadoAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cmdOperacion.setText("Operacion");
        cmdOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOperacionActionPerformed(evt);
            }
        });
        jPanel4.add(cmdOperacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 270, 100));

        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblTablaInicial);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 670, 260));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("Taller Matrices 3");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 630, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 670, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(804, 622));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int nf, nc;
        DefaultTableModel tm, tm2;

        if (txtNumeroDeFilas.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Digite el número de filas", 3);
            txtNumeroDeFilas.requestFocusInWindow();
        } else if (txtNumeroDeColumnas.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Digite el número de columnas", 3);
            txtNumeroDeColumnas.requestFocusInWindow();
        } else if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) == 0) {
            Helper.mensaje(this, "El número de filas no puede ser cero", 3);
            txtNumeroDeFilas.requestFocusInWindow();
            txtNumeroDeFilas.selectAll();
        } else if (Integer.parseInt(txtNumeroDeColumnas.getText().trim()) == 0) {
            Helper.mensaje(this, "El número de columnas no puede ser cero", 3);
            txtNumeroDeColumnas.requestFocusInWindow();
            txtNumeroDeColumnas.selectAll();
        } else if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) < 5 || Integer.parseInt(txtNumeroDeFilas.getText().trim()) > 15) {
            Helper.mensaje(this, "El número de filas solo puede entre 5 y 15", 3);
            txtNumeroDeFilas.requestFocusInWindow();
            txtNumeroDeFilas.selectAll();
        } else if (Integer.parseInt(txtNumeroDeColumnas.getText().trim()) < 5 || Integer.parseInt(txtNumeroDeColumnas.getText().trim()) > 15) {
            Helper.mensaje(this, "El número de columnas solo puede entre 5 y 15", 3);
            txtNumeroDeColumnas.requestFocusInWindow();
            txtNumeroDeColumnas.selectAll();
        } else {
            try {

                nf = Integer.parseInt(txtNumeroDeFilas.getText());
                nc = Integer.parseInt(txtNumeroDeColumnas.getText());

                tm = (DefaultTableModel) tblTablaInicial.getModel();
               
                tm.setRowCount(nf);
                tm.setColumnCount(nc);


                JButton botonesH[] = {cmdLlenadoManual, cmdLlenadoAutomatico, cmdLimpiar};
                JButton botonesD[] = {cmdCrear, cmdOperacion};

                Helper.habilitarBotones(botonesH);
                Helper.deshabilitarBotones(botonesD);
            } catch (NumberFormatException e) {
                Helper.mensaje(this, "Valor no valido", 3);
            }
        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenadoManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoManualActionPerformed
        int nf, nc;
        int n;
        int sw, res;

        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elmento en la posición [" + i + "]" + "[" + j + "]").trim());
                        tblTablaInicial.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.mensaje(this, "Digite un número válido", 3);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            sw = 1;
                            i = nf;
                            j = nc;

                            Helper.porDefectoTabla(tblTablaInicial);
                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        JButton botonesH[] = {cmdOperacion, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdLlenadoManual, cmdLlenadoAutomatico};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLlenadoManualActionPerformed

    private void cmdLlenadoAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenadoAutomaticoActionPerformed
        int nf, nc, n;

        nc = tblTablaInicial.getColumnCount();
        nf = tblTablaInicial.getRowCount();

        for (int i = 0; i < nf; i++) {
            for (int j = 0; j < nc; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
            }

        }

        JButton botonesH[] = {cmdOperacion, cmdLimpiar};
        JButton botonesD[] = {cmdCrear, cmdLlenadoManual, cmdLlenadoAutomatico};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLlenadoAutomaticoActionPerformed

    private void cmdOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOperacionActionPerformed
        int op, aux;
        op = cmbOperaciones.getSelectedIndex();
        

        switch (op) {
            case 0:
                if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) % 2 == 0 || Integer.parseInt(txtNumeroDeColumnas.getText().trim()) % 2 == 0) {
                    Helper.mensaje(this, "El número de filas y columnas debe ser impar para el recorrido 1", 3);
                } else if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) != Integer.parseInt(txtNumeroDeColumnas.getText().trim())) {
                    Helper.mensaje(this, "El número de filas y columnas deben ser la misma para el recorrido 1", 3);
                } else {
                    txtResultado.setText(Helper.recorridoUno(tblTablaInicial));
                }
            break;
            case 1:
                if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) % 2 == 0 || Integer.parseInt(txtNumeroDeColumnas.getText().trim()) % 2 == 0) {
                    Helper.mensaje(this, "El número de filas y columnas debe ser impar para el recorrido 2", 3);
                } else if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) != Integer.parseInt(txtNumeroDeColumnas.getText().trim())) {
                    Helper.mensaje(this, "El número de filas y columnas deben ser la misma para el recorrido 2", 3);
                } else {
                    txtResultado.setText(Helper.recorridoDos(tblTablaInicial));
                }
            break;
            case 2:
                if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) % 2 != 0 || Integer.parseInt(txtNumeroDeColumnas.getText().trim()) % 2 != 0) {
                    Helper.mensaje(this, "El número de filas y columnas debe ser par para el recorrido 1", 3);
                } else if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) != Integer.parseInt(txtNumeroDeColumnas.getText().trim())) {
                    Helper.mensaje(this, "El número de filas y columnas deben ser la misma para el recorrido 1", 3);
                } else {
                    txtResultado.setText(Helper.recorridoTres(tblTablaInicial));
                }
            break;
            case 3:
                if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) % 2 == 0 || Integer.parseInt(txtNumeroDeColumnas.getText().trim()) % 2 == 0) {
                    Helper.mensaje(this, "El número de filas y columnas debe ser impar para el recorrido 4", 3);
                } else if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) != Integer.parseInt(txtNumeroDeColumnas.getText().trim())) {
                    Helper.mensaje(this, "El número de filas y columnas deben ser la misma para el recorrido 4", 3);
                } else {
                    txtResultado.setText(Helper.recorridoCuatro(tblTablaInicial));
                }
            break;
            case 4:
                if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) % 2 == 0 || Integer.parseInt(txtNumeroDeColumnas.getText().trim()) % 2 == 0) {
                    Helper.mensaje(this, "El número de filas y columnas debe ser impar para el recorrido 5", 3);
                } else if (Integer.parseInt(txtNumeroDeFilas.getText().trim()) != Integer.parseInt(txtNumeroDeColumnas.getText().trim())) {
                    Helper.mensaje(this, "El número de filas y columnas deben ser la misma para el recorrido 5", 3);
                } else {
                    txtResultado.setText(Helper.recorridoCinco(tblTablaInicial));
                }
            break;
            
        }

        JButton botonesH[] = {cmdOperacion, cmdLimpiar};
        JButton botonesD[] = {cmdLlenadoManual, cmdLlenadoAutomatico};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdOperacionActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed

        txtNumeroDeFilas.setText("");
        txtNumeroDeColumnas.setText("");
        txtResultado.setText("");
        txtNumeroDeFilas.requestFocusInWindow();
        cmbOperaciones.setSelectedIndex(0);

        Helper.porDefectoTabla(tblTablaInicial);

        JButton botonesH[] = {cmdCrear, cmdLimpiar};
        JButton botonesD[] = {cmdLlenadoManual, cmdLlenadoAutomatico, cmdOperacion};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbOperaciones;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JButton cmdLlenadoAutomatico;
    private javax.swing.JButton cmdLlenadoManual;
    private javax.swing.JButton cmdOperacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTextField txtNumeroDeColumnas;
    private javax.swing.JTextField txtNumeroDeFilas;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
